# Packaging
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_CONTACT "")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")

if(WIN32)
  set(CPACK_GENERATOR "NSIS64;7Z")

  # 明确指定要打包的组件 (确保包含Runtime组件)
  set(CPACK_COMPONENTS_ALL Runtime)
endif()

# 确保系统运行时库被包含
include(InstallRequiredSystemLibraries)
include(CPack)
